### ISSUE TITLE
Add someone from Scala.js community to SIP/SLIP committee?

### ISSUE THREAD

**Issue by dickwall** [scala/slip#13]
Seems to make sense, Sébastien seems like a potential candidate

**Comment by non** [comment]
If Sébastien is busy or uninterested, another possible candidate might be @InTheNow.

**Comment by ghost** [comment]
Sébastien is for sure way more qualified than me for this! But if you need a reserve candidate(s), I would be more than happy to put my name forward for this.

(And thanks to @non for the suggestion, btw)

**Comment by dickwall** [comment]
Sebastien has agreed to join us

**Comment by ghost** [comment]
:+1: Would have been a bit strange otherwise
