### ISSUE TITLE
Active SLIP List gives 404

### ISSUE THREAD

**Issue by lambdista** [scala/slip#15]
There's a 404 for the active SLIP list: https://github.com/scala/slip/blob/master/text/0022-async.md

**Comment by SethTisue** [comment]
thanks for pointing this out. fixed in https://github.com/scala/slip/commit/813824f5b1409e4d200c93bbdd316bd93269d761. (@dickwall might want to edit further?)

**Comment by dickwall** [comment]
Yeah - that was in there in anticipation of either Jason or Phillip
submitting the SLIP 22 PR and us merging it in. That didn't happen yet. I
reckon we'll have to make that PR, and then make sure Jason and Phillip get
the updates.
