### ISSUE TITLE
Revisit By-name Parameters

### ISSUE THREAD

**Issue by dickwall** [scala/slip#21]
During the September SIP/SLIP committee meeting, the subject of by-name parameters came up related to SIP 24, and Josh Suereth and Dick Wall both noted that the current by-names leads to a very common class of eagerness bugs that are commonly found in functional scala libraries. These eagerness bugs are not caught by the compiler, and sometimes don't cause runtime failures, but do still lead to eager execution of code that should not be executed often without detection at either compile or run time.

It is suggested that we open discussions on a proposal to correct these problems in by-name while we are considering other changes (e.g. SIP 24).

**Comment by SethTisue** [comment]
Closing since this repo is being decommissioned. This issue could be revived under the current SIP process.
