### ISSUE TITLE
SLIP 22 - Async - tracking issue

### ISSUE THREAD

**Issue by dickwall** [scala/slip#22]
Issue for tracking developments on SLIP 22 - Async

https://github.com/scala/slip/blob/master/text/0022-async.md

**Comment by dickwall** [comment]
@retronym says - not quite ready yet. Has a round of work planned over the next few months.

On hold, expected to be in better shape in a few months.

**Comment by SethTisue** [comment]
I understand he'll be working both on technical improvements (lifting some restrictions on what kind of code can appear in async blocks), and improved documentation. (the documentation work overlaps with the work needed to write a proper SLIP for it anyway.)

**Comment by SethTisue** [comment]
This could be revived under the new Scala Platform Process.

last version of the proposal was: https://github.com/scala/slip/blob/cd8f7ae7dba6b7d884e8763f666b1a54005e7108/text/0022-async.md

**Comment by SethTisue** [comment]
last version of the proposal was: https://github.com/scala/slip/blob/cd8f7ae7dba6b7d884e8763f666b1a54005e7108/text/0022-async.md
