### ISSUE TITLE
List meeting schedule/channel in README.md

### ISSUE THREAD

**Issue by metasim** [scala/slip#26]
I know I've seen it somewhere, but can't find it! :-)

**Comment by dwijnand** [comment]
:+1:

**Comment by hamishdickson** [comment]
It is on the slip repo isn't it? (says the guy who couldn't find it last week)
![slip](https://cloud.githubusercontent.com/assets/5042218/10964858/826b34ea-83a1-11e5-8117-101cdf763f66.png)

or do you mean something else?

**Comment by dwijnand** [comment]
The schedule isn't, which would be useful to have somewhere stable.

**Comment by SethTisue** [comment]
this could be taken up by a new coordinator

**Comment by SethTisue** [comment]
I would also suggest listing the committee members and their affiliations.

**Comment by SethTisue** [comment]
Closing since this repo is being decommissioned. (@jvican perhaps that there's still something here for your personal todo list as Process Lead)
