### ISSUE TITLE
Collections overhaul

### ISSUE THREAD

**Issue by dickwall** [scala/slip#27]
An issue for tracking the discourse over a potential collections redesign and overhaul.

For background, please read https://github.com/lampepfl/dotty/issues/818

This issue does not track anything as formal as a SLIP proposal currently, it is merely a community placeholder for discussions and potential experiments/designs. Please add comments and/or links below with potential designs or discussions.

**Comment by dickwall** [comment]
@djspiewak's gist on a potential approach: https://gist.github.com/djspiewak/2ae2570c8856037a7738

**Comment by kevinwright** [comment]
+1 for serious consideration of @djspiewak's proposal, given the strength of response it got on twitter, I think that he's quite elegantly captured a lot of the community's concerns

**Comment by SethTisue** [comment]
Closing since this repo is being decommissioned. This is being taken up by Lightbend and the Scala Center for Scala 2.13.
