### ISSUE TITLE
Backticks in String Interpolation SIP tracking

### ISSUE THREAD

**Issue by dickwall** [scala/slip#3]
Contact Kevin Wright re: current state of Backticks support in String interpolation

**Comment by dickwall** [comment]
Kevin has already been contacted and has taken action on this. Need someone, perhaps Kevin, to summarize current status in email to scalaslip@gmail.com, or on here, or both prior to next meeting ideally

**Comment by dickwall** [comment]
Som Snytt has an impl at https://github.com/scala/scala/pull/4663

**Comment by dickwall** [comment]
Previous PR: https://github.com/scala/scala.github.com/pull/297#issuecomment-125258784

**Comment by kevinwright** [comment]
My main observation when proposing this was that "wrap it in backticks" is a common idiom within the Scala language for making _anything_ valid as an identifier.
- It has an odd mix of characters? Wrap it in backticks
- It's a keyword? Wrap it in backticks
- Referencing an existing id in pattern matching and don't want to bind a new value? Wrap it in backticks

Wrapping something in backticks to make it valid has now become a broadly adopted pattern, and uniquely not honouring this in string interpolation breaks the principle of least surprise.

**Comment by SethTisue** [comment]
mailing list thread: https://groups.google.com/d/msg/scala-internals/5iW7BcNa41E/3jhwUSFwMyYJ

**Comment by SethTisue** [comment]
another mailing list thread: https://groups.google.com/d/msg/scala-debate/HKe0BbiPkM8/xxYJke3pUAMJ

**Comment by dickwall** [comment]
Request for status update for Sept 10th SLIP meeting

**Comment by dickwall** [comment]
Rejected due to lack of support overall, and concerns that adding this conformance will actually make the rules less consistent (Martin's argument), as in: there are going to be differences in what identifiers are valid anyway, his view is that it is better to have just one valid set of identifiers off the bat - alpha-numerics, and put anything else inside of {}s like now.
