### ISSUE TITLE
decommission this repository

### ISSUE THREAD

**Issue by SethTisue** [scala/slip#35]
suggested approach, off the top of my head:

* leave the repo in place so old links to discussions remain good
* close all the issues and PRs and use "lock conversation" to prevent further comments
* replace the README with something that says where to go instead

I'm not sure if GitHub offers any other features for "archiving" a repo besides the "lock conversation" thing

**Comment by mdedetrich** [comment]
> leave the repo in place so old links to discussions remain good

This is critical, the SLIP for scala-json-ast still has a huge amount of relevant information which needs to remain

**Comment by SethTisue** [comment]
I closed all the issues and PRs (except this one which isn't all done yet).

**Comment by jvican** [comment]
Your approach is perfect. Thanks for the work @SethTisue.
